name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Generate ZIP file
        run: zip -r deploy.zip . -x "node_modules/*" ".git/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: luizalabs-challenge-backend
          environment_name: luizalabs-challenge-backend-lb-e-env
          region: us-east-1
          version_label: ${{ github.sha }}
          version_description: Deploy automático via GitHub Actions
          deployment_package: deploy.zip
          wait_for_deployment: true
          wait_for_environment_recovery: true
          recovery_wait_time: 30
